[package]
name = "AutoFire"
version = "0.0.1"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "83641d3f083762f31700060e5e95fbb1cbc28bf0" }
MasterChef = { local= "../MasterChef" }

[addresses]
Depolyer = "0x317df9dda493d7cb9b8d5597e64e0dac1a519376fa8fff9cb485a778638dedc3"
ResourceAccount = "0xe055fa95038473bd57a0ae41ff31f58f0e38b8c5fd4b4c4892240899680c133e"